name: Reviewdog
on: [pull_request]
jobs:
  vale:
    name: runner / vale
    runs-on: nebula-runners
    steps:
      - uses: actions/checkout@v2.3.4 #checkout@v2
      - uses: errata-ai/vale-action@reviewdog
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          #REVIEWDOG_GITHUB_APITOKEN : ${{secrets.GITHUB_TOKEN}}
        with:
          version: latest
          files: docs/
          filter_mode: nofilter # added, nofilter, diff_context, file, nofilter
          reporter: github-pr-review # github-pr-check, github-pr-review, github-check
          # fail_on_error: true
          debug: true
          level: suggestion